[package]
name = "frontdoor"
version.workspace = true
edition.workspace = true

[dependencies]
dgv-frontdoor = { path = "../../crates/frontdoor" }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = "0.3.20"
anyhow = { workspace = true }
