{{- if and .Values.frontdoor.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "degov.fullname" . }}-frontdoor
  labels:
    {{- include "degov.componentLabels" (dict "component" "frontdoor" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "degov.componentSelectorLabels" (dict "component" "frontdoor" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}

