[package]
name = "kube-operator"
version.workspace = true
edition.workspace = true

[dependencies]
dgv-kube-operator = { path = "../../crates/kube-operator" }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = "0.3.20"
anyhow = { workspace = true }
