[package]
name = "degov-core"
version.workspace = true
edition.workspace = true

[dependencies]
ssi-dids = "0.2.1"
tokio = { workspace = true }
serde = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
serde_json = { workspace = true }
