{{- if and .Values.kubeOperator.enabled .Values.kubeOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "degov.serviceAccountName" . }}
  labels:
    {{- include "degov.componentLabels" (dict "component" "kube-operator" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.kubeOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

