{{- if .Values.office.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "degov.fullname" . }}-office
  labels:
    {{- include "degov.componentLabels" (dict "component" "office" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
spec:
  type: {{ .Values.office.service.type }}
  ports:
    - port: {{ .Values.office.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "degov.componentSelectorLabels" (dict "component" "office" "Values" .Values "Chart" .Chart "Release" .Release) | nindent 4 }}
{{- end }}

