services:
  # Specify three fdbserver processes.
  fdb-coordinator:
    image: foundationdb/foundationdb:${FDB_VERSION}
    ports:
      - 4500:4500/tcp
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    platform: "linux/amd64"

  fdb-server-1:
    depends_on:
      - fdb-coordinator
    image: foundationdb/foundationdb:${FDB_VERSION}
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    platform: "linux/amd64"

  fdb-server-2:
    depends_on:
      - fdb-coordinator
    image: foundationdb/foundationdb:${FDB_VERSION}
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
    platform: "linux/amd64"

  # Bring up the application so that it depends on the cluster.
  app:
    depends_on:
      - fdb-coordinator
      - fdb-server-1
      - fdb-server-2
    build:
      context: ../../../
      dockerfile: packaging/docker/cli/Dockerfile
      args:
        FDB_VERSION: ${FDB_VERSION}
    ports:
      - 8080:8080/tcp
    entrypoint: ["/app/start-server.bash"]
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_API_VERSION: ${FDB_API_VERSION}
    platform: "linux/amd64"
