[package]
name = "dgv-identity-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
# dgv-identity = { path = "../identity" }
uniffi = "0.29.0"
uniffi_macros = "0.29.0"

[workspace]
