[package]
name = "chancelor"
version.workspace = true
edition.workspace = true

[dependencies]
dgv-chancelor = { path = "../../crates/chancelor" }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = "0.3.20"
anyhow = { workspace = true }
